### ISSUE TITLE
docs_dir from included mkdocs.yml

### ISSUE THREAD

**Issue by haneul** [backstage/mkdocs-monorepo-plugin#41] opened 2021-03-23 11:07 UTC
https://backstage.github.io/mkdocs-monorepo-plugin/limitations/ lists this as know limitation
* In an included mkdocs.yml, it currently looks for the relative docs/ folder and does not respect the docs_dir value.

Any plans to change this? sometimes it doesn't make much sense to create docs directory separately when some directory already has documents.

**Comment by Fox32** [comment] 2021-03-23 18:04
Duplicate of #40?

**Comment by iamEAP** [comment] 2021-03-23 18:08
Thanks for triaging @Fox32!  @haneul, would you mind adding your use-case in #40?  We can continue the conversation there.

**Closed by iamEAP** 2021-03-23 18:08 UTC

**Comment by haneul** [comment] 2021-03-23 23:46
sure I'll add there. I thought the use case was slightly different but may still fall into the same issue.
